import { fileURLToPath, URL } from 'node:url'
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import prerender from '@prerenderer/rollup-plugin'

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    prerender({
      routes: ['/'],
      renderer: '@prerenderer/renderer-puppeteer',
      rendererOptions: {
        // Tells Puppeteer to wait for this event before snapping the HTML
        renderAfterDocumentEvent: 'custom-render-trigger',
        maxConcurrentRoutes: 1, // Only 1 route, so we only need 1 concurrent worker
        skipThirdPartyRequests: true,
      },
      postProcess(renderedRoute) {
        // Clean up localhost URLs generated by the build environment
        renderedRoute.html = renderedRoute.html.replace(
          /\b(?:href|src|content)=("([^"]*)"|'([^']*)')/gi,
          (attribute) =>
            attribute.replace(
              /https?:\/\/(?:localhost|127\.0\.0\.1)(?::\d+)?/gi,
              'https://mustafa-azmi.netlify.app',
            ),
        )

        // Saves the prerendered output as index-root.html
        renderedRoute.outputPath = 'index-root.html'
      },
    }),
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
})
