<script setup>
import { ref } from 'vue'
import ProjectCard from './ProjectCard.vue'
import ProjectModal from './ProjectModal.vue'

const selectedProject = ref(null)

const projects = [
  {
    id: 1,
    title: 'Note-Nest',
    category: 'Website',
    image: '/images/note-nest.png',
    description: 'A personal note-taking app built with Vue 3 using the Composition API. Users can create, edit, delete, and organize text notes with tags. Data is persisted locally with Local Storage.',
    tags: ['Vue', 'CSS', 'JavaScript'],
    link: 'https://github.com/Mustafa21102005/note-nest'
  },
  {
    id: 2,
    title: 'ScanTrack',
    category: 'Website',
    image: '/images/scan-track.png',
    description: 'ScanTrack is a web-based attendance management system designed for universities. It allows students to check in to classes by scanning a QR code generated by the lecturer for each lecture.',
    tags: ['Laravel', 'Blade', 'CSS', 'JS', 'Dashboard'],
    link: 'https://github.com/Mustafa21102005/scantrack'
  }
]

const openModal = (project) => {
  selectedProject.value = project
}

const closeModal = () => {
  selectedProject.value = null
}
</script>

<template>
  <section id="works" class="s-works target-section">
    <div class="row">
      <div class="column lg-12">
        <h2 class="text-pretitle">Recent Works</h2>
        <p class="h1">
          A curated set of projects demonstrating my experience across full stack web development.
        </p>

        <ul class="folio-list row block-lg-one-half block-stack-on-1000">
          <ProjectCard v-for="project in projects" :key="project.id" :project="project" @open="openModal" />
        </ul>
      </div>

      <ProjectModal :project="selectedProject" :open="!!selectedProject" @close="closeModal" />
    </div>
  </section>
</template>
